# Generated by Django 2.2.7 on 2020-03-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
